# Increase the heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Enable parallel builds
org.gradle.parallel=true

# Enable build caching
org.gradle.caching=true

# Use AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
